### ISSUE TITLE
Google verification fails

### ISSUE THREAD

**Issue by jensz12** [cosmocode/dokuwiki-plugin-oauthgoogle#2]
The icon and style for the Google Login button needs to be updated. Google will reject your verification request with the following reason otherwise
"You need to update the Google sign-in button on your project’s homepage so that it complies with the Google sign-in branding guidelines"

https://developers.google.com/identity/branding-guidelines

![Screenshot_20220320-120642](https://user-images.githubusercontent.com/1682377/159159971-3c2313db-d115-4e24-903d-5cd82afc3d54.png)

**Comment by splitbrain** [comment]
Can you explain why a verification is necessary at all? I don't remember having to verify the app?

**Comment by divadsn** [comment]
> Can you explain why a verification is necessary at all? I don't remember having to verify the app?

Because otherwise Google won't allow you to use their OAuth service once you reach a limit of 100 users during "testing".

https://support.google.com/cloud/answer/7454865?hl=en
