### ISSUE TITLE
Error 400: redirect_uri_mismatch

### ISSUE THREAD

**Issue by ImhotepDE** [cosmocode/dokuwiki-plugin-oauthgoogle#5]
### Issue Description

Hello everyone,

From one day to the next I get this error: Could it be that Google has changed something in the process?

Thank you 

<img width="858" alt="image" src="https://github.com/user-attachments/assets/d8d68ea5-0b28-4609-b74e-c4b6e37a11e2">

**Comment by splitbrain** [comment]
you did not configure the correct redirect uri
